### PR TITLE
1.9.2 compatiblity fix

### PR DESCRIPTION
**Pull request by tobsch**
hey there,

in 1.9.2 when: is no longer supported for case statements.
hope this helps others to use your ext with 1.9.2

### CODE REVIEW

**Comment by saturnflyer** [comment]
Thanks for the contribution! This will be a great help to have for 1.9 when radiant is ready.

I find it more readable to have simple when/then on one line. Would you be willing to take time to change this to 
`when "$" then match[0]` for the layout of the code?

I'd prefer not to use jeweler anymore either, so I'll update that to a manually created file eventually too.

**Comment by tobsch** [comment]
Okay, I changed it.
Using Jewler is just fine but you have to check in the generated gemspec IMHO.
This makes it possible to refer to the gem in a Gemfile with git as source.

**Comment by ghost** [comment]
@saturnflyer i just had to make the same change to `when:` to upgrade a largish site to 1.9.2. any chance of merging this and releasing a new gem?

**Comment by saturnflyer** [comment]
Sorry for the delay, I had set this aside and forgot to get back to it. Thanks so much for the patch @tobsch!

**Pull request merged**
